# Generated by Django 3.1.3 on 2020-11-19 12:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201119_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('unavailable', 'Indisponível'), ('deleted', 'Deletado')], default='unavailable', max_length=20),
        ),
    ]
