# Generated by Django 3.1.3 on 2020-11-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201119_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('unavailable', 'Indisponível'), ('deleted', 'Deletado')], max_length=20),
        ),
    ]
